name: Ejecutar Tests (Front y Back)

on:
  push:
    branches: ["main", "DEV"]
  pull_request:
    branches: ["main", "DEV"]

jobs:
  # 1. JOB DE TESTS UNITARIOS E INTEGRACIÓN BACKEND
  backend-tests:
    runs-on: ubuntu-latest
    concurrency:
      group: reports-${{ github.ref_name }}
      cancel-in-progress: false
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
        
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Instalar dependencias del Backend
        working-directory: ./backend
        run: npm install
        
      # AÑADIDO: --run para evitar modo watch, --no-file-parallelism para forzar ejecución secuencial
      - name: Ejecutar Tests del Backend (Unitarios + Integración)
        working-directory: ./backend
        run: npm test -- --run --no-file-parallelism
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }} # Conecta el secreto de GitHub con el entorno de Node
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }} # Conecta el secreto de GitHub con el entorno de Node
          
      - name: upload report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TEST_REPORTS }}
          external_repository: Dokt0r/GPS-2025-2026_test_report
          publish_dir: backend/test-report
          destination_dir: back/${{ github.ref_name }}

  # 2. JOB DE TESTS UNITARIOS FRONTEND
  frontend-tests:
    runs-on: ubuntu-latest
    concurrency:
      group: reports-${{ github.ref_name }}
      cancel-in-progress: false
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4
        
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Instalar dependencias del Frontend
        working-directory: ./frontend
        run: npm install
        
      - name: Ejecutar Tests del Frontend (Vitest)
        working-directory: ./frontend
        run: npm test -- --run
        
      - name: upload report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TEST_REPORTS}}
          external_repository: Dokt0r/GPS-2025-2026_test_report
          publish_dir: frontend/test-report
          destination_dir: front/${{ github.ref_name }}

  # 3. DESPLIEGUE
  desplegar-vercel:
    # CORREGIDO: Sintaxis YAML arreglada para los needs
    needs: [backend-tests, frontend-tests] 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Avisar a Vercel
        run: curl -X POST ${{ secrets.VERCEL_WEBHOOK }}
